spring:
    application:
        name: preorder

    mail:
        host: smtp.gmail.com
        port: 587
        username: hashfractal@gmail.com
        password: rawo hmdw ilah vpfg
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true


    datasource:
        url: jdbc:mariadb://localhost:3306/preorder
        username: dehkartes
        password: 3589
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace

secret:
    AES256: qsad45f1asd651as65g1