server:
    port: 8000

spring:
    application:
        name: gateway
    config:
        import:
            secret.yml
    cloud:
        gateway:
            routes:
                - id: user
                  uri: http://localhost:8080/
                  predicates:
                    - Path=/user/**
                - id: product
                  uri: http://localhost:8081/
                  predicates:
                      - Path=/product/**
                - id: order
                  uri: http://localhost:8082/
                  predicates:
                      - Path=/order/**